# Generated by Django 5.0.6 on 2024-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_order_is_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
