# Generated by Django 5.0.6 on 2024-07-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_is_sale_remove_order_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
